config/routes.rb
Rails.application.routes.draw do
  resources :platform_colors
  resources :comments
  resources :likes
  resources :mylists
  resources :follows
  resources :news
  resources :sources
  resources :platforms
  resources :animes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'register', to: 'users#register', as: 'register'
  post 'register', to: 'users#create_new_user'

  get 'login', to: 'users#login_page', as: 'login'
  post 'login', to: 'users#login'

  get 'logout', to: 'users#logout', as: 'logout'

  get 'feed', to: 'users#feed', as: 'feed'

  get 'my_list', to: 'users#my_list', as: 'my_list'
  post 'my_list', to: 'mylists#save_my_list'
  delete 'my_list', to: 'mylists#unsave_my_list'

  get 'home', to: 'animes#home', as: 'home'

  get 'anime_page/:name', to: 'animes#anime_page', as: 'anime_page'
  get 'source_page/:name', to: 'sources#source_page', as: 'source_page'
  get 'news_page/:id', to: 'news#news_page', as: 'news_page'

  post 'like', to: 'likes#like_asn', as: 'like_manager'
  delete 'like', to: 'likes#unlike_asn'

  post 'follow', to: 'follows#follow_a', as: 'follow_manager'
  delete 'follow', to: 'follows#unfollow_a'

  post 'comment', to: 'comments#comment_asn', as: 'comment_manager'
  delete 'comment', to: 'comments#uncomment_asn'
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :anime
  has_one_attached :image

  validates :name, presence: true
  validates :category, presence: true
  validates :desc, presence: true

  has_many :likes, as: :likeable
  has_many :liked_users, through: :likes, source: :user, class_name: 'User'

  has_many :comments, as: :commentable
  has_many :commented_users, through: :comments, source: :user, class_name: 'User'

  def this_user_liked(user_id)
    return self.liked_users.include?(User.find_by(id: user_id))
  end

  def get_liked_user_names
    return self.liked_users.order('name').pluck('name').join(' ')
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[ show edit update destroy ]

  # GET /sources or /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1 or /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources or /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: "Source was successfully created." }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1 or /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: "Source was successfully updated." }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1 or /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: "Source was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def source_page
    @source = Source.where("name LIKE ?", "%#{params[:name].split('_').join('%')}%").first
    @comment = Comment.new
    if @source == nil
      redirect_to home_path, alert: "There are no source with that name"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_params
      params.require(:source).permit(:name, :category, :desc, :anime_id, :image)
    end
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/sources/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@source) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :category
    = f.input :desc
    = f.association :anime
    = f.input :image

  .form-actions
    = f.button :submit, class: "btn btn-primary", style: "margin: 5px 0px;"

app/views/sources/edit.html.haml
%h1 Editing source

= render 'form'

= link_to 'Show', @source
\|
= link_to 'Back', sources_path

app/views/sources/index.html.haml
%h1 Listing sources

%table.row-border#sources_index_table
  %thead
    %tr
      %th Name
      %th Category
      %th Desc
      %th Anime
      %th Image
      %th
      %th
      %th

  %tbody
    - @sources.each do |source|
      %tr
        %td= source.name
        %td= source.category
        %td{style: "white-space: pre-wrap;"}= source.desc
        %td= Anime.find(source.anime_id).name
        %td
          - if source.image.attached?
            = image_tag source.image, style: "height: 250px; display: block; margin-left: auto; margin-right: auto;"
        %td= link_to 'Show', source
        %td= link_to 'Edit', edit_source_path(source)
        %td= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Source', new_source_path

:javascript
  $(document).ready( function () {
    $('#sources_index_table').DataTable({
      "ordering": true,
      "order": [[0,'asc']]
    });
  } );

app/views/sources/new.html.haml
%h1 New source

= render 'form'

= link_to 'Back', sources_path

app/views/sources/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @source.name
%p
  %b Category:
  = @source.category
%p{style: "white-space: pre-wrap;"}
  %b Desc:
  = @source.desc
%p
  %b Anime:
  = Anime.find(@source.anime_id).name
%p
  %b Image:
  - if @source.image.attached?
    = image_tag @source.image, style: "height: 250px; display: block;"

= link_to 'Edit', edit_source_path(@source)
\|
= link_to 'Back', sources_path

app/views/sources/source_page.html.haml
%h1.text-primary= @source.name

.row
    .col-4
        - if @source.image.attached?
            = image_tag @source.image, class: "h-auto w-75 m-3"
        
    .col
        %h5
            %b Type :
            = @source.category
        %br
        %h5
            %b Description :
        %p.fs-6{style: "white-space: pre-wrap;"}= @source.desc

.row
    .col-2.position-relative
        %h5.like_lister.fs-4.text-decoration-none.text-success.bg-transparent.position-absolute.top-50.start-50.translate-middle{data:"#{@source.get_liked_user_names}"}= "Like : #{@source.liked_users.count}"
    .col-1
        - if @source.this_user_liked(session[:user_id])
            = button_to 'Unlike', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Source", likeable_id: @source.id}}, method: :delete, class: "btn btn-danger m-2"
        - else
            = button_to 'Like', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Source", likeable_id: @source.id}}, method: :post, class: "btn btn-primary m-2"

.row
    %h4.fw-bold Comment
    = simple_form_for(@comment, url: comment_manager_path) do |f|

        .form-inputs
            = f.input :msg
            = f.hidden_field :user_id, value: session[:user_id]
            = f.hidden_field :commentable_type, value: "Source"
            = f.hidden_field :commentable_id, value: @source.id

        .form-actions.mt-2
            = f.button :submit, "Submit Comment", class: "btn btn-primary"

.row
    - @source.comments.order('created_at DESC').each do |c|
        .card.m-3.p-1.w-75
            .card-header
                .row
                    .col-1
                        %h5.fs-4= c.user.name
                    .col.position-relative
                        - if c.user_id == session[:user_id]
                            = button_to "Delete comment", comment_manager_path, params: {comment:{id: c.id}}, method: :delete, class: "btn btn-danger p-1 position-absolute top-0 end-0"
            .card-body
                %p.card-text.fs-6{style: "white-space: pre-wrap;"}= c.msg
            .card-footer
                %small= c.created_at.getlocal

= render 'layouts/modal'