config/routes.rb
Rails.application.routes.draw do
  resources :platform_colors
  resources :comments
  resources :likes
  resources :mylists
  resources :follows
  resources :news
  resources :sources
  resources :platforms
  resources :animes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'register', to: 'users#register', as: 'register'
  post 'register', to: 'users#create_new_user'

  get 'login', to: 'users#login_page', as: 'login'
  post 'login', to: 'users#login'

  get 'logout', to: 'users#logout', as: 'logout'

  get 'feed', to: 'users#feed', as: 'feed'

  get 'my_list', to: 'users#my_list', as: 'my_list'
  post 'my_list', to: 'mylists#save_my_list'
  delete 'my_list', to: 'mylists#unsave_my_list'

  get 'home', to: 'animes#home', as: 'home'

  get 'anime_page/:name', to: 'animes#anime_page', as: 'anime_page'
  get 'source_page/:name', to: 'sources#source_page', as: 'source_page'
  get 'news_page/:id', to: 'news#news_page', as: 'news_page'

  post 'like', to: 'likes#like_asn', as: 'like_manager'
  delete 'like', to: 'likes#unlike_asn'

  post 'follow', to: 'follows#follow_a', as: 'follow_manager'
  delete 'follow', to: 'follows#unfollow_a'

  post 'comment', to: 'comments#comment_asn', as: 'comment_manager'
  delete 'comment', to: 'comments#uncomment_asn'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, uniqueness: { case_sensitive: false }, presence: true
    validates :email, uniqueness: { case_sensitive: false }, presence: true
    validates :password, presence: true, length: { minimum: 3 }, confirmation: { case_sensitive: true }

    has_many :follows
    has_many :followed_animes, through: :follows, source: :anime, class_name: 'Anime'

    has_many :mylists
    has_many :saved_animes, through: :mylists, source: :anime, class_name: 'Anime'

    has_many :likes
    has_many :liked_animes, through: :likes, source: :likeable, source_type: 'Anime'
    has_many :liked_sources, through: :likes, source: :likeable, source_type: 'Source'
    has_many :liked_news, through: :likes, source: :likeable, source_type: 'News'

    has_many :comments
    has_many :commented_animes, through: :comments, source: :commentable, source_type: 'Anime'
    has_many :commented_sources, through: :comments, source: :commentable, source_type: 'Source'
    has_many :commented_news, through: :comments, source: :commentable, source_type: 'News'

    def get_feed_anime
        return Anime.select("*,(day_in_week+7-#{Time.now.getlocal.wday})%7 AS wday").where(id: self.followed_animes.pluck('id'), on_air: true).order("on_air DESC, wday, show_time")
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in, only: %i[ feed my_list ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def register
    @user = User.new
  end

  def create_new_user
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to home_path, notice: "User was successfully created." }
      else
        format.html { render :register, status: :unprocessable_entity }
      end
    end
  end

  def login_page
    @user = User.new
  end

  def login
    @user = User.find_by(email: user_params[:email])
    if @user == nil
      redirect_to login_path, alert: "Email or Password incorrect"
    else
      if @user.authenticate(user_params[:password])
        redirect_to feed_path, notice: "You logged in successfully"
        session[:user_id] = @user.id
      else
        redirect_to login_path, alert: "Email or Password incorrect"
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to home_path, notice: "You logged out successfully"
  end

  def feed
    @animes = @user.get_feed_anime
    @news = News.order('created_at DESC')
  end

  def my_list
    @lists = @user.mylists
  end

  private
    def logged_in
      if session[:user_id]
        @user = User.find(session[:user_id])
      else
        redirect_to login_path, alert: "Please log in first"
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit, class: "btn btn-primary", style: "margin: 5px 0px;"

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/feed.html.haml
%h1
    You are logged in as :
    %b= @user.name

- if alert != nil
    %p.alert.alert-danger#alert{role: "alert"}= alert
- if notice != nil
    %p.alert.alert-success#notice{role: "alert"}= notice

= link_to 'My List', my_list_path, class: "btn btn-primary", style: 'margin: 5px;'

.row
    .col-8
        = render 'animes/animes_list'
    .col
        = render 'news/news_list'

app/views/users/index.html.haml
%h1 Listing users

%table.row-border#users_index_table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

:javascript
  $(document).ready( function () {
    $('#users_index_table').DataTable();
  } );

app/views/users/login_page.html.haml
%h1 Login

- if alert != nil
    %p.alert.alert-danger#alert{role: "alert"}= alert
- if notice != nil
    %p.alert.alert-success#notice{role: "alert"}= notice

= simple_form_for(@user, url: login_path) do |f|
    .form-inputs
        = f.input :email
        = f.input :password

    .form-actions.mt-2
        = f.button :submit, "Login", class: "btn btn-primary", style: 'margin: 5px;'
        = link_to 'Register', register_path, class: 'btn btn-info', style: 'margin: 5px;'
        = link_to 'Cancel', home_path, class: "btn btn-warning", style: "margin: 5px;"

app/views/users/my_list.html.haml
%h1 Watch List

%table.cell-border#watch_lists_index_table
  %thead
    %tr
      %th Name
      %th Added at
      %th Remove from the list

  %tbody
    - @lists.each do |list|
      - @anime = list.anime
      %tr
        %td= link_to @anime.name, anime_page_path(@anime.name.parameterize.underscore), class: "fs-5 text-decoration-none text-primary"
        %td= list.created_at.getlocal
        %td= button_to 'Remove', my_list_path, params: {mylist:{user_id: list.user_id, anime_id: list.anime_id}}, method: :delete, class: "btn btn-danger mx-auto", style: "display: block;"

:javascript
  $(document).ready( function () {
    $('#watch_lists_index_table').DataTable({
      "ordering": true,
      "order": [[0,'asc']]
    });
  } );

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/register.html.haml
%h1 Register

= simple_form_for(@user, url: register_url) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit, 'Register', class: "btn btn-primary", style: "margin: 5px;"
    = link_to 'Cancel', home_path, class: "btn btn-warning", style: "margin: 5px;"

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path