config/routes.rb
Rails.application.routes.draw do
  resources :platform_colors
  resources :comments
  resources :likes
  resources :mylists
  resources :follows
  resources :news
  resources :sources
  resources :platforms
  resources :animes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'register', to: 'users#register', as: 'register'
  post 'register', to: 'users#create_new_user'

  get 'login', to: 'users#login_page', as: 'login'
  post 'login', to: 'users#login'

  get 'logout', to: 'users#logout', as: 'logout'

  get 'feed', to: 'users#feed', as: 'feed'

  get 'my_list', to: 'users#my_list', as: 'my_list'
  post 'my_list', to: 'mylists#save_my_list'
  delete 'my_list', to: 'mylists#unsave_my_list'

  get 'home', to: 'animes#home', as: 'home'

  get 'anime_page/:name', to: 'animes#anime_page', as: 'anime_page'
  get 'source_page/:name', to: 'sources#source_page', as: 'source_page'
  get 'news_page/:id', to: 'news#news_page', as: 'news_page'

  post 'like', to: 'likes#like_asn', as: 'like_manager'
  delete 'like', to: 'likes#unlike_asn'

  post 'follow', to: 'follows#follow_a', as: 'follow_manager'
  delete 'follow', to: 'follows#unfollow_a'

  post 'comment', to: 'comments#comment_asn', as: 'comment_manager'
  delete 'comment', to: 'comments#uncomment_asn'
end

app/models/news.rb
class News < ApplicationRecord
  has_one_attached :image

  validates :headline, presence: true
  validates :content, presence: true

  has_many :likes, as: :likeable
  has_many :liked_users, through: :likes, source: :user, class_name: 'User'

  has_many :comments, as: :commentable
  has_many :commented_users, through: :comments, source: :user, class_name: 'User'

  def this_user_liked(user_id)
    return self.liked_users.include?(User.find_by(id: user_id))
  end

  def get_liked_user_names
    return self.liked_users.order('name').pluck('name').join(' ')
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /news or /news.json
  def index
    @news = News.order('created_at DESC')
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def news_page
    @news = News.find_by(id: params[:id])
    @comment = Comment.new
    if @news == nil
      redirect_to home_path, alert: "There are no news with that id"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:headline, :content, :image)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@news) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :headline
    = f.input :content
    = f.input :image

  .form-actions
    = f.button :submit, class: "btn btn-primary", style: "margin: 5px;"

app/views/news/_news_list.html.haml
- @news.each do |n|
    .card.m-3.w-100.news-card
        .card-header.text-start
            %h6= link_to n.headline, news_page_path(n.id), class: "fw-bold text-decoration-none text-success"
        .card-body
            .row
                .col-5
                    - if n.image.attached?
                        = image_tag n.image, class: "h-auto w-100"
                .col
                    %small= n.created_at.getlocal
                    %p.card-text{style: "white-space: pre-wrap;"}= truncate(n.content,length:100)
        .card-footer
            - if n.this_user_liked(session[:user_id])
                = button_to 'Unlike', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "News", likeable_id: n.id}}, method: :delete, class: "btn btn-danger", style: "display: block; margin: auto;"
            - else
                = button_to 'Like', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "News", likeable_id: n.id}}, method: :post, class: "btn btn-primary", style: "display: block; margin: auto;"

app/views/news/edit.html.haml
%h1 Editing news

= render 'form'

= link_to 'Show', @news
\|
= link_to 'Back', news_index_path

app/views/news/index.html.haml
%h1 Listing news

%table.row-border#news_index_table
  %thead
    %tr
      %th Headline
      %th Content
      %th Image
      %th Date Time
      %th
      %th
      %th

  %tbody
    - @news.each do |news|
      %tr
        %td= news.headline
        %td{style: "white-space: pre-wrap;"}= news.content
        %td
          - if news.image.attached?
            = image_tag news.image, style: "height: 250px; display: block; margin-left: auto; margin-right: auto;"
        %td= news.created_at.getlocal
        %td= link_to 'Show', news
        %td= link_to 'Edit', edit_news_path(news)
        %td= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New News', new_news_path

:javascript
  $(document).ready( function () {
    $('#news_index_table').DataTable({
      "ordering": true,
      "order": [[3,'desc']]
    });
  } );

app/views/news/new.html.haml
%h1 New news

= render 'form'

= link_to 'Back', news_index_path

app/views/news/news_page.html.haml
%h1.text-primary.fs-3= @news.headline

.row
    .col-4
        - if @news.image.attached?
            = image_tag @news.image, class: "h-auto w-75 m-3"
        
    .col
        %br
        %h5= @news.created_at.getlocal
        %p.fs-6{style: "white-space: pre-wrap;"}= @news.content

.row
    .col-2.position-relative
        %h5.like_lister.fs-4.text-decoration-none.text-success.bg-transparent.position-absolute.top-50.start-50.translate-middle{data:"#{@news.get_liked_user_names}"}= "Like : #{@news.liked_users.count}"
    .col-1
        - if @news.this_user_liked(session[:user_id])
            = button_to 'Unlike', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "News", likeable_id: @news.id}}, method: :delete, class: "btn btn-danger m-2"
        - else
            = button_to 'Like', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "News", likeable_id: @news.id}}, method: :post, class: "btn btn-primary m-2"

.row
    %h4.fw-bold Comment
    = simple_form_for(@comment, url: comment_manager_path) do |f|

        .form-inputs
            = f.input :msg
            = f.hidden_field :user_id, value: session[:user_id]
            = f.hidden_field :commentable_type, value: "News"
            = f.hidden_field :commentable_id, value: @news.id

        .form-actions.mt-2
            = f.button :submit, "Submit Comment", class: "btn btn-primary"

.row
    - @news.comments.order('created_at DESC').each do |c|
        .card.m-3.p-1.w-75
            .card-header
                .row
                    .col-1
                        %h5.fs-4= c.user.name
                    .col.position-relative
                        - if c.user_id == session[:user_id]
                            = button_to "Delete comment", comment_manager_path, params: {comment:{id: c.id}}, method: :delete, class: "btn btn-danger p-1 position-absolute top-0 end-0"
            .card-body
                %p.card-text.fs-6{style: "white-space: pre-wrap;"}= c.msg
            .card-footer
                %small= c.created_at.getlocal

= render 'layouts/modal'

app/views/news/show.html.haml
%p#notice= notice

%p
  %b Headline:
  = @news.headline
%p{style: "white-space: pre-wrap;"}
  %b Content:
  = @news.content
%p
  %b Image:
  - if @news.image.attached?
    = image_tag @news.image, style: "height: 250px; display: block;"

= link_to 'Edit', edit_news_path(@news)
\|
= link_to 'Back', news_index_path