config/routes.rb
Rails.application.routes.draw do
  resources :platform_colors
  resources :comments
  resources :likes
  resources :mylists
  resources :follows
  resources :news
  resources :sources
  resources :platforms
  resources :animes
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'register', to: 'users#register', as: 'register'
  post 'register', to: 'users#create_new_user'

  get 'login', to: 'users#login_page', as: 'login'
  post 'login', to: 'users#login'

  get 'logout', to: 'users#logout', as: 'logout'

  get 'feed', to: 'users#feed', as: 'feed'

  get 'my_list', to: 'users#my_list', as: 'my_list'
  post 'my_list', to: 'mylists#save_my_list'
  delete 'my_list', to: 'mylists#unsave_my_list'

  get 'home', to: 'animes#home', as: 'home'

  get 'anime_page/:name', to: 'animes#anime_page', as: 'anime_page'
  get 'source_page/:name', to: 'sources#source_page', as: 'source_page'
  get 'news_page/:id', to: 'news#news_page', as: 'news_page'

  post 'like', to: 'likes#like_asn', as: 'like_manager'
  delete 'like', to: 'likes#unlike_asn'

  post 'follow', to: 'follows#follow_a', as: 'follow_manager'
  delete 'follow', to: 'follows#unfollow_a'

  post 'comment', to: 'comments#comment_asn', as: 'comment_manager'
  delete 'comment', to: 'comments#uncomment_asn'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :synopsis, presence: true
  validates :day_in_week, presence: true
  validates :show_time, presence: true
  validates :episode, presence: true

  has_many :platforms
  has_many :sources

  has_many :follows
  has_many :followed_users, through: :follows, source: :user, class_name: 'User'

  has_many :mylists
  has_many :saved_users, through: :mylists, source: :user, class_name: 'User'

  has_many :likes, as: :likeable
  has_many :liked_users, through: :likes, source: :user, class_name: 'User'

  has_many :comments, as: :commentable
  has_many :commented_users, through: :comments, source: :user, class_name: 'User'

  def this_user_liked(user_id)
    return self.liked_users.include?(User.find_by(id: user_id))
  end

  def this_user_followed(user_id)
    return self.followed_users.include?(User.find_by(id: user_id))
  end

  def this_user_saved(user_id)
    return self.saved_users.include?(User.find_by(id: user_id))
  end

  def get_liked_user_names
    return self.liked_users.order('name').pluck('name').join(' ')
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]

  # GET /animes or /animes.json
  def index
    # get list of animes
    # the top is the ones that is airing today
    @animes = Anime.select("*,(day_in_week+7-#{Time.now.getlocal.wday})%7 AS wday").order("on_air DESC, wday, show_time")
  end

  # GET /animes/1 or /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes or /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: "Anime was successfully created." }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1 or /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: "Anime was successfully updated." }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1 or /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: "Anime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def home
    @animes = Anime.select("*,(day_in_week+7-#{Time.now.getlocal.wday})%7 AS wday").order("on_air DESC, wday, show_time")
    @news = News.order('created_at DESC')
  end

  def anime_page
    @anime = Anime.where("name LIKE ?", "%#{params[:name].split('_').join('%')}%").first
    @comment = Comment.new
    if @anime == nil
      redirect_to home_path, alert: "There are no anime with that name"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:name, :synopsis, :day_in_week, :show_time, :on_air, :episode, :image)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_animes_list.html.haml
- @platform_color = Hash[PlatformColor.all.pluck(:platform, :color)]
- @animes.each do |a|
    .card.m-3.w-100.anime-card
        .card-body
            .row
                .col-4
                    - if a.image.attached?
                        = image_tag a.image, class: "h-auto w-75"
                .col-8
                    %h4= link_to a.name, anime_page_path(a.name.parameterize.underscore), class: "card-title fs-3 fw-bold text-decoration-none text-primary"
                    %h5.card-text
                        %b Day :
                        = "#{Date::DAYNAMES[a.day_in_week]}"
                        %b Time :
                        = "#{a.show_time.getlocal.strftime("%H:%M UTC %z")}"
                    %h5.card-text
                        %b Episode :
                        = "#{a.episode}"
                    %h5.card-text
                        %b On Air Status :
                        = a.on_air
                    - a.platforms.order('name').each do |p|
                        - if @platform_color.include?(p.name)
                            = link_to p.name, p.link, class: "btn btn-#{@platform_color[p.name]} card-text m-1 text-white"
                            %br
                        - else
                            = link_to p.name, p.link, class: "btn btn-success card-text m-1"
                            %br
        .card-footer
            .row
                .col
                    - if a.this_user_liked(session[:user_id])
                        = button_to 'Unlike', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Anime", likeable_id: a.id}}, method: :delete, class: "btn btn-danger", style: "display: block; margin: auto;"
                    - else
                        = button_to 'Like', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Anime", likeable_id: a.id}}, method: :post, class: "btn btn-primary", style: "display: block; margin: auto;"
                .col
                    - if a.this_user_followed(session[:user_id])
                        = button_to 'Unfollow', follow_manager_path, params: {follow:{user_id: session[:user_id], anime_id: a.id}}, method: :delete, class: "btn btn-danger", style: "display: block; margin: auto;"
                    - else
                        = button_to 'Follow', follow_manager_path, params: {follow:{user_id: session[:user_id], anime_id: a.id}}, method: :post, class: "btn btn-primary", style: "display: block; margin: auto;"

app/views/animes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@anime) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :synopsis
    = f.input :day_in_week, hint: 'Sunday is 0 and so on.'
    = f.input :show_time, hint: 'Input time in UTC'
    = f.input :on_air
    = f.input :episode
    = f.input :image

  .form-actions
    = f.button :submit, class: "btn btn-primary", style:"margin: 5px 0px;"

app/views/animes/anime_page.html.haml
%h1.text-primary= @anime.name

.row
    .col-4
        - if @anime.image.attached?
            = image_tag @anime.image, class: "h-auto w-75 m-3"
        
    .col
        %h5
            %b Day :
            = "#{Date::DAYNAMES[@anime.day_in_week]}"
            %b Time :
            = "#{@anime.show_time.getlocal.strftime("%H:%M UTC %z")}"
        %h5
            %b Episode :
            = "#{@anime.episode}"
        %h5
            %b On Air Status :
            = @anime.on_air
        %h5
            %b Synopsis :
        %p.fs-6{style: "white-space: pre-wrap;"}= @anime.synopsis
        %h5
            %b Source :
        - @anime.sources.order('category').each do |s|
            = link_to s.category, source_page_path(s.name.parameterize.underscore), class: "m-2 fs-5 fw-normal text-decoration-none text-primary"
        %br
        - @platform_color = Hash[PlatformColor.all.pluck(:platform, :color)]
        - @anime.platforms.order('name').each do |p|
            - if @platform_color.include?(p.name)
                = link_to p.name, p.link, class: "btn btn-#{@platform_color[p.name]} card-text m-2 text-white"
            - else
                = link_to p.name, p.link, class: "btn btn-success card-text m-2"

.row
    .col-2.position-relative
        %h5.like_lister.fs-4.text-decoration-none.text-success.bg-transparent.position-absolute.top-50.start-50.translate-middle{data:"#{@anime.get_liked_user_names}"}= "Like : #{@anime.liked_users.count}"
    .col-1
        - if @anime.this_user_liked(session[:user_id])
            = button_to 'Unlike', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Anime", likeable_id: @anime.id}}, method: :delete, class: "btn btn-danger m-2"
        - else
            = button_to 'Like', like_manager_path, params: {like:{user_id: session[:user_id], likeable_type: "Anime", likeable_id: @anime.id}}, method: :post, class: "btn btn-primary m-2"
    .col-1
        - if @anime.this_user_followed(session[:user_id])
            = button_to 'Unfollow', follow_manager_path, params: {follow:{user_id: session[:user_id], anime_id: @anime.id}}, method: :delete, class: "btn btn-danger m-2"
        - else
            = button_to 'Follow', follow_manager_path, params: {follow:{user_id: session[:user_id], anime_id: @anime.id}}, method: :post, class: "btn btn-primary m-2"
    .col-1
        - if @anime.this_user_saved(session[:user_id])
            = button_to 'Remove from Watch List', my_list_path, params: {mylist:{user_id: session[:user_id], anime_id: @anime.id}}, method: :delete, class: "btn btn-danger m-2"
        - else
            = button_to 'Add to Watch List', my_list_path, params: {mylist:{user_id: session[:user_id], anime_id: @anime.id}}, method: :post, class: "btn btn-info m-2 text-white"

.row
    %h4.fw-bold Comment
    = simple_form_for(@comment, url: comment_manager_path) do |f|

        .form-inputs
            = f.input :msg
            = f.hidden_field :user_id, value: session[:user_id]
            = f.hidden_field :commentable_type, value: "Anime"
            = f.hidden_field :commentable_id, value: @anime.id

        .form-actions.mt-2
            = f.button :submit, "Submit Comment", class: "btn btn-primary"

.row
    - @anime.comments.order('created_at DESC').each do |c|
        .card.m-3.p-1.w-75
            .card-header
                .row
                    .col-1
                        %h5.fs-4= c.user.name
                    .col.position-relative
                        - if c.user_id == session[:user_id]
                            = button_to "Delete comment", comment_manager_path, params: {comment:{id: c.id}}, method: :delete, class: "btn btn-danger p-1 position-absolute top-0 end-0"
            .card-body
                %p.card-text.fs-6{style: "white-space: pre-wrap;"}= c.msg
            .card-footer
                %small= c.created_at.getlocal

= render 'layouts/modal'

app/views/animes/edit.html.haml
%h1 Editing anime

= render 'form'

= link_to 'Show', @anime
\|
= link_to 'Back', animes_path

app/views/animes/home.html.haml
%h1 Home

- if alert != nil
    %p.alert.alert-danger#alert{role: "alert"}= alert
- if notice != nil
    %p.alert.alert-success#notice{role: "alert"}= notice

.row
    .col-8
        = render 'animes/animes_list'
    .col
        = render 'news/news_list'

app/views/animes/index.html.haml
%h1 Listing animes

%table.row-border#animes_index_table
  %thead
    %tr
      %th Name
      %th Synopsis
      %th{style: "display: none;"} Day in week (after processed with current week day)
      %th Day in week
      %th Show time
      %th On air
      %th Episode
      %th Image
      %th
      %th
      %th

  %tbody
    - @animes.each do |anime|
      %tr
        %td= anime.name
        %td{style: "white-space: pre-wrap;"}= anime.synopsis
        -# %td= anime.synopsis.first(500)
        -# %td= truncate(anime.synopsis, length: 200)
        %td{style: "display: none;"}= "#{(anime.day_in_week+7-Time.now.getlocal.wday)%7}"
        %td= Date::DAYNAMES[anime.day_in_week]
        %td= anime.show_time.getlocal.strftime("%H:%M UTC %z")
        %td= anime.on_air
        %td= anime.episode
        -# %td= anime.image
        %td
          - if anime.image.attached?
            = image_tag anime.image, style: "height: 250px; display: block; margin-left: auto; margin-right: auto;"
        %td= link_to 'Show', anime
        %td= link_to 'Edit', edit_anime_path(anime)
        %td= link_to 'Destroy', anime, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Anime', new_anime_path

:javascript
  $(document).ready( function () {
    $('#animes_index_table').DataTable({
      "ordering": true,
      "order": [[2,'asc'], [4,'asc']]
    });
  } );

app/views/animes/new.html.haml
%h1 New anime

= render 'form'

= link_to 'Back', animes_path

app/views/animes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @anime.name
%p{style: "white-space: pre-wrap;"}
  %b Synopsis:
  = @anime.synopsis
%p
  %b Day in week:
  = Date::DAYNAMES[@anime.day_in_week]
%p
  %b Show time:
  = @anime.show_time.getlocal.strftime("%H:%M UTC %z")
%p
  %b On air:
  = @anime.on_air
%p
  %b Episode:
  = @anime.episode
%p
  %b Image:
  - if @anime.image.attached?
    = image_tag @anime.image, style: "height: 250px; display: block;"

= link_to 'Edit', edit_anime_path(@anime)
\|
= link_to 'Back', animes_path